### ISSUE TITLE
Snappy Nextcloud, Beitrag

### ISSUE THREAD

**Issue by scubamuc** [LinuxNews-de/host-it-yourself#2]
Servus beinand,
schöne Idee mit dem Selfhosting! Hier ist mein Beitrag: https://scubamuc.github.io.

**Comment by Hanibal1963** [comment]
Sollten die Beiträge nicht auf deutsch verfasst sein?
Ich frag ja nur.

**Comment by scubamuc** [comment]
Servus @Hanibal1963, boarisch geht a... als mich das Nextcloud Snap Team einlud deren Dokumentation und Wiki zu verfassen, übersetzte ich bereits meine deutschen Texte und entschied mich es dabei zu belassen. Es wäre eine Rolle rückwärts jetzt alles zurück zu übersetzen? Schade wenn es so nicht passt.

**Comment by slalabs** [comment]
Nextcloud Tutorial wird kommen, aber nicht als Snap sondern auf einem LEPP-Stack. Der Großteil unserer Leserschaft ist Anti-Snap.

**Comment by scubamuc** [comment]
@slalabs, na dann... ist wohl nichts?
