### ISSUE TITLE
Maybe migrate to an Microsoft GitHub alternative?

### ISSUE THREAD

**Issue by buhtz** [LinuxNews-de/host-it-yourself#21]
The repo is young. Have you considered an alternative code hoster like Codeberg.org, SourceHut, ...?

**Comment by slalabs** [comment]
What added value do you hope to gain from this?

**Comment by colttt** [comment]
ich glaube das ist eher ideeler natur.. was natürlich auch nachvollziehbar ist:
 * als Linuxer ist MS nunmal böse
 * als deutsche Linuxseite sollte man auch einen deutschen Codehoster bevorzugen - so bleibt alles im lande
 * man unterstützt damit indirekt die Verbreitung freier Software  (in dem Fall Forgejo)

**Comment by HilkopterBob** [comment]
In my opinion, GitHub is deeply ingrained in the workflows of many developers, making it a crucial part of the development process. Exploring an alternative code hosting platform could unnecessarily complicate established practices. As a fellow Linux Workstation user, I find it challenging to see the rationale behind fundamentally changing platforms merely to avoid a Microsoft product. GitHub serves as a cornerstone for numerous open-source projects, and its widespread adoption should be acknowledged and respected.

**Comment by buhtz** [comment]
Dear Nick,
thanks for your feedback.

> In my opinion, GitHub is deeply ingrained in the workflows of many developers

I disagree. You mean "git" not Microsoft GitHub. It is not a big deal to switch between different code hosters if they all do support `git`.

>I find it challenging to see the rationale behind fundamentally changing platforms merely to avoid a Microsoft product.

It is not about "Microsoft Hatting". It is not only about Microsoft. Even before Microsoft took over GitHub it was an issue to discuss if GitHub is an appropriate choice for a FOSS project. After Microsoft took it over the decision is just a bit easier.

> GitHub serves as a cornerstone for numerous open-source projects

That is marketing speech and not true. It is the other way around. The FOSS projects are the "cornerstone" for Microsoft GitHub.

And this is my point. LinuxNews.de is not a one man tiny project. It is a public news platform and should behave as an example and role model to others.

> its widespread adoption should be acknowledged and respected.

1 Mio. flies... There is no value in counting users when MS establish a locked-in effect because MS need the users to sell them as their real product.

**Comment by HilkopterBob** [comment]
Hey @buhtz,

Thanks for sharing your opinion. Just to clarify, I was referring to GitHub.

Let's avoid expanding the discussion too much and consider a community vote.

**Comment by slalabs** [comment]
> And this is my point. LinuxNews.de is not a one man tiny project. It is a public news platform and should behave as an example and role model to others.

That's why we choose Github. If someone has zero knowledge of this git stuff, he can use a search engine. The majority of tutorials out there are written for Github. We would rather not exclude anyone just because they don't know how to use this git thing. 

My first thought was codeberg.org, but at the time this project was born, codeberg had some serious issues with their uptime. 

I like the idea of a community vote, so please vote:

[KLICK](https://github.com/LinuxNews-de/host-it-yourself/discussions/24)

**Comment by buhtz** [comment]
> > And this is my point. LinuxNews.de is not a one man tiny project. It is a public news platform and should behave as an example and role model to others.
> 
> That's why we choose Github. If someone has zero knowledge of this git stuff, he can use a search engine. The majority of tutorials out there are written for Github.

Regarding the "tutorials" there is no relevant difference between Microsoft GitHub and Gitea/Gitlab/Forgjo when it comes creating Issues and PRs.

> We would rather not exclude anyone just because they don't know how to use this git thing.

No need for "git".

> My first thought was codeberg.org, but at the time this project was born, codeberg had some serious issues with their uptime.

That is unfair. The last two big downtimes where because of attacks. Codeberg was very transparent about this. They are also transparent about the downtimes in the past and reacted very quick and well with increasing and improving their infrastructure. That all is very suprising to me when you think about that Codeberg is a tiny voluntary project with limited ressources compared to Microsoft.

**Comment by HilkopterBob** [comment]
@buhtz
It seems to me that you are actually interested in providing users to your platform rather than helping the project...

Apart from that - it may be that an attack has reduced uptime, but that doesn't bring it back and makes the service overall unreliable.

**Comment by slalabs** [comment]
Open for voting, closing this for now
