### ISSUE TITLE
und nun?!

### ISSUE THREAD

**Issue by colttt** [LinuxNews-de/host-it-yourself#22]
Soo..
da ich nicht weiss wie man den Versursacher des ganzen anders erreichen kann frag ich das mal hier:
Wie ist der Plan, nach anfänglicher Euphorie und einigen Requests wie soll es jetzt weiter gehen? So nen Faden wäre nicht schlecht, der ein oder andere hat auch gepostet das man helfen würde was zu schreiben.. Wie? Wann? Wohin?

**Comment by HilkopterBob** [comment]
Schreib einen Artikel den du beisteuern kannst und mache einen PR?

**Comment by slalabs** [comment]
Bisher haben wir einen PR erhalten, diverse Artikel habe ich vorbereitet. Nach unserem baldigen Relaunch geht es hier los. Ein "Contribute" File wäre eine gute Idee, ist vermerkt.
