### ISSUE TITLE
VDI für kleine Umgebungen

### ISSUE THREAD

**Issue by glimfindel** [LinuxNews-de/host-it-yourself#7]
Virtual Desktop Umgebungen werden beispielsweise für Schulungen, gesicherte Administrationsumgebungen oder einfach nur als Arbeitsplatz "Desktops" benötigt. Das Ganze soll plattformunabhängig über einen Browser funktionieren, mit freier Software aufgebaut und übersichtlich-minimalistisch in der Zusammenstellung der Komponenten sein, also: 
* Linux (Debian/Ubuntu)
* Apache
* Guacamole
* VirtualBox
* (+ MariaDB)

**Comment by slalabs** [comment]
Danke für deinen PR! Der Artikel ist gut, mir tun sich nur eine Frage auf da ich es selbst nicht einsetzte:

Warum nennst du explizit Debian 11 und nicht 12? Tippfehler? Bug in Deb12? Fehlende Pakete? Nicht getestet?

**Comment by glimfindel** [comment]
Oh ja, danke für den Hinweis! Es funktioniert natürlich auch mit Debian 12! Ich habe die Installation mit Siduction Initial aufgesetzt, als es noch die 11er war und den Artikel im Nachhinein nicht mehr korrigiert. Getestet habe ich es also mit Debian 11 und 12, sowie Ubuntu 20.04 und 22.04.
